---
- name: copy web site to remote server
  hosts: test-server
  become: yes
  gather_facts: yes
  tasks:
    - name: copy_files
      copy: src=index.html dest=/var/www/html/
    - name: copy_files
      copy: src=readme.txt dest=/var/www/html/
  #  - name: move connetct
   #   command: mv /var/www/html/index.html /tmp/
