---
- name: Install net-tools
  hosts: 172.31.40.93
  become: true
  gather_facts: true
  tasks:
    - name: install net-tools
      package: name=net-tools state=present
#     package: name=net-tools state=absent ( to delete package set as absent)
