---
- name: install nginx on test server
  hosts: 172.31.40.93
  become: yes
  gather_facts: true
  tasks:
    - name: install nginx
      apt: name=nginx state=present
        #apt: name=nginx state=present
    - name: start/stop nginx
      command: systemctl start nginx
